version: '3.8'

services:
  app:
    image: expense-tracker
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      MONGODB_URI: mongodb://root:${DB_PASSWORD}@mongo:27017/your-db-name?authSource=admin
    ports:
      - "80:80"  # Change this if your app runs on a different port
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"  # This port is used for local access to MongoDB; remove or change as needed
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  default:
    driver: bridge